### ISSUE TITLE
Self update

### ISSUE THREAD

**Issue by WINGS-N** [ServerJars/updater#7]
Add serverjars updater self update

**Comment by briannastatic** [comment]
Cool idea! Maybe we will :)

**Comment by DebugOk** [comment]
Looks like this was added in commit #14

**Comment by SpraxDev** [comment]
> Looks like this was added in commit #14

A update notifier has been added but I like the idea of ServerJars automatically downloading new versions (enabled by default, disabled by choice).

If the Minecraft community taught me one thing about itself, it's that updates don't matter and if they do, they are performed sloppy. I'm still not sure if ServerJars should just download the recommended JRE version automatically and use it if not configured otherwise when I see some of the issued people have at the Discord server.

**Comment by DebugOk** [comment]
I think just leaving an notifier is fine. There don't seem to be updates often and ServerJars will still work, even if outdated whereas Paper or Spigot needs to be updated to fix bugs and exploits

**Comment by SpraxDev** [comment]
You are probably right.

Added in v3.0.0 (#14)
